### PR TITLE
Feature/uh2000-header-and-footer

### PR DESCRIPTION
**Pull request by Jandres02**
### Pull Request Description

**Summary:**

This Pull Request completes the implementation of the header and footer components for the website. Both components are now fully responsive, including for mobile devices.

**Details:**

- **Header:**
  - Includes logo on the left.
  - Search bar with a submit button in the center.
  - Links to account and cart on the right.

- **Footer:**
  - Divided into multiple sections for company information, contact links, payment methods, and policy details.
  - Responsive design to ensure proper display on various screen sizes.

**Responsive Design:**
- The header and footer have been optimized for mobile devices.
- The layout adapts smoothly to different screen widths, including smartphones.

imagen_2024-09-02_001411321
imagen_2024-09-02_001424080
imagen_2024-09-02_001442841
imagen_2024-09-02_001514316

### CODE REVIEW

**Review by EdgarGXI — APPROVED** [review]
Good structure, all requirements checked, maybe design could be improved to make it stand out a bit more

**Comment by EdgarGXI** [comment]
Responsive should be handled better for the designated dimensions, it works, nonetheless sizes could be more appealing

**Comment by Caltafulla** [comment]
It seems to me to be a complete design that meets what was requested. Personally, I would only make a small adjustment of proportions to the payment entities. Apart from that, I think it's an excellent job.

**Review by Caltafulla — APPROVED** [review]

**Review by Val-jimenez — APPROVED** [review]
The design and colors are according to the color palette chosen in the group. The logo design was excellent.

**Pull request merged**
