### PR TITLE
Feature/uh2000-header-and-footer

### PR DESCRIPTION
**Pull request by Jandres02**
### Pull Request Description

**Summary:**

This Pull Request completes the implementation of the header and footer components for the website. Both components are now fully responsive, including for mobile devices.

**Details:**

- **Header:**
  - Includes logo on the left.
  - Search bar with a submit button in the center.
  - Links to account and cart on the right.

- **Footer:**
  - Divided into multiple sections for company information, contact links, payment methods, and policy details.
  - Responsive design to ensure proper display on various screen sizes.

**Responsive Design:**
- The header and footer have been optimized for mobile devices.
- The layout adapts smoothly to different screen widths, including smartphones.

imagen_2024-09-01_184211345
imagen_2024-09-01_184223936
imagen_2024-09-01_184236074
imagen_2024-09-01_184306752

### CODE REVIEW

**Comment by Somils12** [comment]
The page looks great, it is attractive and meets all the requirements! Just one recommendation, the color of the discount letter could be a little lighter compared to the background.

The header and footer look great, I really like the structure of the elements and I think everything looks very organized. Additionally, the page meets all the requirements.

**Comment by Somils12** [comment]
The header and footer look great, I really like the structure of the elements and I think everything looks very organized. Additionally, the page meets all the requirements.

**Review by EdgarGXI — APPROVED** [review]
Good structure, all requirements checked, maybe design could be improved to make it stand out a bit more

**Comment by EdgarGXI** [comment]
Responsive should be handled better for the designated dimensions, it works, nonetheless sizes could be more appealing

**Pull request closed without merging**
