### PR TITLE
Feature/uh2001 create main page

### PR DESCRIPTION
**Pull request by EdgarGXI**
Main page completed, leaving placeholders for the header and footer. Minor design adjustments may be required.

image
image
image

### CODE REVIEW

**Comment by Val-jimenez** [comment]
The design is good and the photos look good quality. The color could be changed in the future.

**Review by Val-jimenez — APPROVED** [review]
The design is good and the photos look good quality. The color could be changed in the future.

**Comment by Jandres02** [comment]
I consider that it meets the requirements, the design is pleasing to the eye.

**Review by Jandres02 — APPROVED** [review]

**Comment by Caltafulla** [comment]
It seems to me that it has a design that is quite pleasing to the eye that meets the requirements.

**Review by Caltafulla — APPROVED** [review]

**Comment by Jandres02** [comment]
as a suggestion, I think that the advertising banners should have the same border-radius as the page elements to make it look harmonious.

**Comment by Somils12** [comment]
The page looks great, it is attractive and meets all the requirements! Just one recommendation, the color of the discount letter can be placed a little lighter in relation to the background.

**Pull request merged**
